import Head from 'next/head';
import React from 'react';
import { BurgerMenu } from 'components/BurgerMenu';
import { HouseIcon } from 'components/BurgerMenu/HouseIcon';
export const Header: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-white opacity-90'>
        <header className='absolute top-0 left-0 right-0 '>
          <nav className='container mx-auto px-6 md:px-12 py-4'>
            <div className='md:flex justify-between items-center'>
              <div className='flex justify-between items-center'>
                <a href='#' className='text-white'>
                  <HouseIcon />
                </a>
                <div className='md:hidden'>
                  <BurgerMenu />
                </div>
              </div>
              <div className='hidden md:flex items-center'>
                <a className='text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300'>
                  About us
                </a>
                <a className='text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300'>
                  Calendar
                </a>
                <a className='text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300'>
                  Contact us
                </a>
              </div>
            </div>
          </nav>
        </header>
      </div>
    </>
  );
};
